global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

